version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ../frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always
    networks:
      - alclate-network

  db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - '3306:3306'
#    restart: always
    networks:
      - alclate-network
    
  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '8080:8080'
#    restart: always
    networks:
      - alclate-network

  backend:
    image: 'canals/php:latest'
    env_file: ./.env
    ports:
      - '2080:80'
    volumes:
      - ../backend/public:/var/www/html
      - ../backend:/var/www
    working_dir: /var/www/
    networks:
      - alclate-network
    depends_on:
      - db

networks:
  alclate-network:
    driver: bridge